# Generated by Django 4.2.3 on 2023-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='channel_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
