# Generated by Django 4.2.3 on 2023-08-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_statistics', '0002_statistics_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='channel_name',
        ),
    ]
