# Generated by Django 4.2.3 on 2023-08-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_statistics', '0007_alter_statistics_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='user',
        ),
    ]
