# Generated by Django 4.2.3 on 2023-08-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_statistics', '0010_remove_statistics_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
